name: linter
on: push

jobs:
  super-linter:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run super-linter@v3
        uses: github/super-linter@v3