name: linter
on: push

jobs:
  super-linter:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run super-linter@v3
        uses: github/super-linter@v3.17.0

  deployToDev: 
    name: Deploy code to dev
    needs: [super-linter]
    environment: 
      name: Dev
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying to dev

  deployToProd: 
    name: Deploy code to prod
    if: github.event.ref == 'refs/heads/main'
    needs: [super-linter]
    environment: 
      name: Dev
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying to prod