name: linter
on: push

jobs:
  super-linter:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run linting job
        uses: ./.github/actions/testing.yml

  deployToDev: 
    name: Deploy code to dev
    runs-on: ubuntu-latest
    needs: [super-linter]
    environment: 
      name: Dev
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying to dev

  deployToProd: 
    name: Deploy code to prod
    needs: [deployToDev]
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: 
      name: Dev
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying to prod